### ISSUE TITLE
Preisanpassungen

### ISSUE THREAD

**Issue by JaJost** [jwanner83/saftlade.com#2]
Eigentlich passt alles aber leider habe ich gemerkt das die Preise sehr komisch sind. Ich denke das ist ein Bug das diese so tief sind. Bitte um schnelle Behebung des Fehlers!

LG Jannik Jost

**Comment by jwanner83** [comment]
Ist gut, ich werde die Preise auf 40 Rappen pro Eistee anpassen. Die Redbulls werden ab jetzt kostenlos sein.
